### ISSUE TITLE
How to check if exec succeeded or not

### ISSUE THREAD

**Issue by gaultier** [mafintosh/ssh-exec#2]
Is it possible to do something like this:

```
exec.on('error' , function(err) {
  //do something
});
```

In the code I see that `duplex` emits an `error` event, how to catch it?

**Comment by zxqfox** [comment]
:+1:

**Comment by jasonjifly** [comment]
It can't work for me, shh failed to connect to Server, there're some errors reported, but stream.on("error" ...) cann't handle it.

**Comment by Student007** [comment]
+1

**Comment by mafintosh** [comment]
This should be fixed it latest ssh-exec
