### ISSUE TITLE
Streamed connection doesn't output anything

### ISSUE THREAD

**Issue by EwanValentine** [mafintosh/ssh-exec#4]
Going by your example, I tried doing

```
process.stdin
            .pipe(exec('echo try typing something; cat -', hostInstance))
            .pipe(process.stdout);
```

It connects, but when I run a command, nothing happens?

Cheers in advance!

**Comment by mafintosh** [comment]
It should just echo what you type (thats what `cat -` does). Does this not work?

**Comment by EwanValentine** [comment]
Ahh yes, that works. I was trying to implement this in order to start a terminal session as though you'd just ssh'd into a server in the traditional way. However, I don't get the host name or etc? If I run

```
process.stdin.pipe(exec('sh', hostInstance)).pipe(process.stdout);
```

I get a shell session, but there's no host name or anything, it's just blank? 

Sorry if this doesn't make any sense, having trouble explaining this one!

**Comment by mafintosh** [comment]
Ah. What you wanna do is

``` js
var exec = require('ssh-exec')

process.stdin
  .pipe(exec('/bin/bash --rcfile .bashrc -i', 'user@remote.com'))
  .pipe(process.stdout)
```

**Comment by EwanValentine** [comment]
Ahaaaa! Fantastic. Thanks for that :) Great library by the way.

**Comment by mafintosh** [comment]
:+1: You probably want to set `process.stdin.setRawMode(true)` as well
