### ISSUE TITLE
pipe some data to the remote process

### ISSUE THREAD

**Issue by irom77** [mafintosh/ssh-exec#6]
Hey, sorry maybe doing something wrong but can't find anything in the output file, see below:

var exec = require('ssh-exec');
var fs = require('fs');
file = fs.createWriteStream('rep-output.txt');
    process.stdin
        .pipe(exec(command, host))
        .pipe(file);
    file.end();

here it is:
$ cat rep-output.txt 
$ 
but because 'command' is 'touch output.txt' I can see it executed correctly on remote 'host':
$ ls -l output.txt 
-rw-rw-r-- 1 irekr irekr 0 Jul  4 10:53 output.txt

**Comment by irom77** [comment]
sorry it's fine after removing //file.end(); But when I schedule this code in Linux cron then doesn't work . I tried absolute paths etc didn't help . it works fine (sends email) if I comment all this code and i.e. ask to email something to me i.e. /*process.stdin .pipe(exec(command, host)) .pipe(file);*/ email.send(); I wonder why ?

**Comment by mafintosh** [comment]
i don't understand your 2nd example. could you clarify it?

**Comment by irom77** [comment]
it was issue in my code, sorry
