### ISSUE TITLE
how do I handle connection errors ?

### ISSUE THREAD

**Issue by irom77** [mafintosh/ssh-exec#8]
If I get connection error i.e. ssh2 'USERAUTH_FAILURE ' how do I handle it, where to put err callback ?

**Comment by asessa** [comment]
exec('ls -lh', 'ubuntu@my-remote.com').on('error', function(e) {
  console.log('ERROR', e);
}).pipe(process.stdout)

**Comment by mafintosh** [comment]
what @asessa said
