### ISSUE TITLE
Add a Callback

### ISSUE THREAD

**Issue by mtwalsh** [mafintosh/ssh-exec#9]
Hi,

I'm using this package within a Meteor JS application and it would be a great help if the exec() function could be passed a Callback.

Apologies if this is already possible, I didn't have any luck trying.

**Comment by mafintosh** [comment]
what should the callback be called with?

**Comment by mtwalsh** [comment]
Wow, thanks for the quick response!

At the moment I'm just using this code example:

```
exec('ls -lh', {
  user: 'ubuntu',
  ...
}).pipe(process.stdout)
```

Which does output the console output (from the remote server) to the Meteor console but I want to be able to save the remote server console output, so using a Callback would be preferred, so something like this:

```
exec('ls -lh', {
  user: 'ubuntu',
  ...
}, function(err, stdout, stderr) {
  console.log(stdout);
});
```
I hope that answers the question?!  I'm afraid this is my first Meteor JS application so I'm a bit of a newbie.

**Comment by mafintosh** [comment]
Sounds good. Added a callback api similar to what you described above in 1.4.0

**Comment by mafintosh** [comment]
There is documentation for it in the readme as well.

**Comment by mtwalsh** [comment]
Wow again!  Thanks for sorting that so quickly, much appreciated.

**Comment by mtwalsh** [comment]
Yep, that's working perfectly.

**Comment by mafintosh** [comment]
:tada:
